### ISSUE TITLE
Gravatar Image does not update

### ISSUE THREAD

**Issue by jacenrkohler** [andMYhacks/infosec_mentors_project#14]
I've verified that my Gravatar account is setup properly.
I've resubmitted  my InfoSecMentor profile with the proper email address.
But my profile still shows the default Gravatar logo.

**Comment by jacenrkohler** [comment]
Odd, it works now.
I doubt you've had time to fix it, so maybe it just takes some time to sync up with Gravatar?

**Comment by andMYhacks** [comment]
@jacenrkohler that's possible... It could be a cacheing issue with your browser that wasn't forcing it to update/change right away. I'll close this for now, and re-open if it happens to other users.
