### ISSUE TITLE
Additional skills

### ISSUE THREAD

**Issue by trevorbryant** [andMYhacks/infosec_mentors_project#24]
Would it be possible to add an additional skills for Security Auditing and Security Configuration Management? The auditor role being more of an Information Assurance position that I see a lot of new, entry level graduates or even first-timers into infosec coming into. The auditing role typical entails configuration reviews and interviews against a target compliance framework.

Security Configuration Management (I look at this as engineering, welcome all feedback) where we not only work towards an automated service catalog, but ensuring the services provided are supplied in a compliant and hardened state (config, patches, scans, etc).

**Comment by infosecmentors** [comment]
@trevorbryant Thanks for the suggestion. We'll work this in.

**Comment by andMYhacks** [comment]
@trevorbryant Happy to add these skills.

Do you want to take a crack at adding these and submitting a pull request? You would add it to the skills list in the `app/main/forms.py` file. I'm happy to do it on your behalf if you'd rather not :+1:

**Comment by andMYhacks** [comment]
I would suggest adding the skills as generic "Auditing" and "Configuration Management"

**Comment by andMYhacks** [comment]
Closed with Pull Request #25 

Great job Trevor!

**Comment by andMYhacks** [comment]
@trevorbryant I've added "Contributor, InfoSec Mentors Project" to your profile on the site. Thanks again!
