### ISSUE TITLE
Add linux as a skill to choose

### ISSUE THREAD

**Issue by alias454** [andMYhacks/infosec_mentors_project#5]
Adding Linux as an option to select as skill for mentoring would be nice in the short-term. In the long-term, adding functionality to add unique skills might make for an interesting community feature.

Regards,
Brandon

**Comment by andMYhacks** [comment]
Totally forgot about this one! Should be really easy to add.

**Comment by andMYhacks** [comment]
Added Windows and Linux Administration as skills.
